---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: _PREFIX_postgres-pv-claim
  labels:
    app: _PREFIX_postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: _PREFIX_postgres-config
  labels:
    app: _PREFIX_postgres
data:
  POSTGRES_DB: _POSTGRES_DB_
  POSTGRES_USER: _POSTGRES_USER_
  POSTGRES_PASSWORD: _POSTGRES_PASSWORD_
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: _PREFIX_postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: _PREFIX_postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: _PREFIX_postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: _PREFIX_postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: _PREFIX_postgres
  name: _DATABASE_SERVICE_NAME_
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: _PREFIX_postgres
