---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: _PREFIX_jenkins-pv-claim
  labels:
    app: _PREFIX_jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
